runtime: python39

env_variables:
  DJANGO_SETTINGS_MODULE: "your_project.settings"
  GOOGLE_APPLICATION_CREDENTIALS: "path/to/your/service-account-key.json"

handlers:
- url: /static
  static_dir: static/
  secure: always

- url: /.*
  script: auto
  secure: always

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10 