runtime: python310

env_variables:
  DJANGO_SETTINGS_MODULE: "batool.settings"
  GOOGLE_APPLICATION_CREDENTIALS: "vlp-web-service-account-key.json"
  PYTHONUNBUFFERED: "1"
  GAE_USE_SOCKETS_HTTPLIB: "true"
  GS_BUCKET_NAME: "vulpis.com.ar"

handlers:
- url: /static
  static_dir: static/
  secure: always

- url: /.*
  script: auto
  secure: always

service_account: vulpis-web@vlp-web.iam.gserviceaccount.com

entrypoint: gunicorn -b :$PORT batool.wsgi:application

beta_settings:
  cloud_sql_instances: vlp-web:us-central1:vlp-web-db

inbound_services:
- warmup  