# Generated by Django 5.1.6 on 2025-02-22 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_handler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('step_type', models.CharField(choices=[('task', 'Task'), ('gateway', 'Gateway'), ('event', 'Event'), ('subprocess', 'Sub Process')], default='task', max_length=20)),
                ('order', models.IntegerField()),
                ('start_time', models.FloatField(help_text='Tiempo de inicio en el video (segundos)')),
                ('end_time', models.FloatField(help_text='Tiempo de fin en el video (segundos)')),
                ('bpmn_id', models.CharField(help_text='Identificador único para BPMN', max_length=50, unique=True)),
                ('is_start_event', models.BooleanField(default=False)),
                ('is_end_event', models.BooleanField(default=False)),
                ('gateway_type', models.CharField(blank=True, choices=[('exclusive', 'Exclusive'), ('parallel', 'Parallel'), ('inclusive', 'Inclusive')], max_length=20, null=True)),
                ('next_steps', models.ManyToManyField(blank=True, related_name='previous_steps', to='video_handler.step')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='video_handler.video')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('video', 'order')},
            },
        ),
    ]
