# Generated by Django 5.1.6 on 2025-02-22 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_handler', '0002_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='order',
            field=models.PositiveIntegerField(),
        ),
    ]
