# Generated by Django 5.1.6 on 2025-02-22 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_handler', '0003_alter_step_description_alter_step_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='BPMNDiagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xml_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_current', models.BooleanField(default=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bpmn_diagrams', to='video_handler.video')),
            ],
        ),
    ]
