"""
Django settings for batool project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from google.oauth2 import service_account
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Google Cloud Storage
GS_CREDENTIALS = service_account.Credentials.from_service_account_file(
    'vlp-web-service-account-key.json'
)
GS_BUCKET_NAME = 'vulpis.com.ar'
GS_PROJECT_ID = 'vlp-web'
GS_DEFAULT_ACL = None
GS_QUERYSTRING_AUTH = True  # Habilitar URLs firmadas
GS_EXPIRATION = timedelta(hours=1)  # URLs expiran en 1 hora

# Storage configuration
DEFAULT_FILE_STORAGE = 'storages.backends.gcloud.GoogleCloudStorage'
STATICFILES_STORAGE = 'storages.backends.gcloud.GoogleCloudStorage'

# Media and Static files
MEDIA_URL = f'https://storage.googleapis.com/{GS_BUCKET_NAME}/media/'
STATIC_URL = f'https://storage.googleapis.com/{GS_BUCKET_NAME}/static/'

# No local directories in App Engine
if os.getenv('GAE_APPLICATION', None):
    MEDIA_ROOT = None
    STATIC_ROOT = None
    DEBUG = False
else:
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
    STATIC_ROOT = os.path.join(BASE_DIR, 'static')
    os.makedirs(MEDIA_ROOT, exist_ok=True)
    os.makedirs(STATIC_ROOT, exist_ok=True)
    DEBUG = True

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(fajf@9#ys@hx6gtgw2n!c&59icnfnp_6xjxjf3nlpj9c5(aga'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    'vlp-web.uc.r.appspot.com',    # Dominio de App Engine
    'vlp-web.appspot.com',         # Dominio alternativo de App Engine
    'vulpis.com.ar',               # Tu dominio personalizado
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'video_handler',
    'storages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'batool.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'batool.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'vlp_web_db',
        'USER': 'postgres',
        'PASSWORD': 'AdminVlp01A$2025',
        'HOST': '/cloudsql/vlp-web:us-central1:vlp-web-db',
    }
}

# Para desarrollo local
if DEBUG:
    DATABASES['default']['HOST'] = '127.0.0.1'


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# Configuración de medios y estáticos
MEDIA_URL = f'https://storage.googleapis.com/{GS_BUCKET_NAME}/'
STATIC_URL = f'https://storage.googleapis.com/{GS_BUCKET_NAME}/static/'

# Configuración de cookies y CSRF
CSRF_TRUSTED_ORIGINS = [
    'https://vlp-web.uc.r.appspot.com',
    'https://vlp-web.appspot.com',
    'https://vulpis.com.ar',
]

# Desactivar temporalmente algunas configuraciones de seguridad para debugging
SECURE_SSL_REDIRECT = False  # Cambiar a True después
SESSION_COOKIE_SECURE = False  # Cambiar a True después
CSRF_COOKIE_SECURE = False  # Cambiar a True después

# Configuración de logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
